language: python

python:
  - "2.7"
  - "3.2"

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.2"

script:
  - py.test

notifications:
  email: false
  slack:
    secure: FBQgSpZpjeEtfciTab0cxvezkD1PPxdPQ94fHmjqV44iaDY47ZyfODZBpjO6g2Bhhjq26YiFZjlzFjykh4H+YoWCTRzL7+ZBqomUSzLbeR75heyjAfK7+DM3t5PdET2ND5WnMSr/I2GeoKubC2lAAj35lCAWKQAp3EjW+5GDww90m0i+GOSa+btTYIkIQZcDxmcO8rJCe8+/LibEVRcQT7Xv7y/gMfIJOXceW/5DC62CdV4mas14raZn4ZVVCypbqOvv1kxQS4epfe0diYOxOprH6txJKb3MpJw0AHF5rFaZKU7NGb2+BI40OYl7tCE8V+7d3m5Cj+NdhTNeoMhGypT5IFvkQ8vRq4HYbR6NCbZcKw8K+ziY8Hog1PCB5YJGzMjHHtAGXqSp18nsBbiuwZ19+bq5X9Fzkpkzh7th13MEjhM1JUVU8K7U7sOkG3iVVmbMi7oN26sQnGShZ/pyGRQyW1ArvjLGVIII051oJgrWU1oSOXDQM8lcasPD7/+iHHiU8WBz5RaJM9Prh6HmIfpKkxL3llygwDmS0IMZDavVmvDmDq4SxxjkKergyPmTXyCAS6J30pO4aTPspOQU4bkgdv1XJ49euOtHjjXywyuPQZnq3+gtzTf2ewIhcecUkfUq1WXObfzd8rLiRvWIMDY/i0/hNdpsvNo/SYDyc2c=
